version: '3.9'
services:
  php:
    container_name: jobs-php
    networks:
      dominion_net:
        ipv4_address: 15.16.235.5
    build:
      context: ./
      dockerfile: docker/${DOCKER_FILE}
    ports:
      - "${PHP_PORT}:80"
    #    links:
    #      - mysql
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
volumes:
  centosphp8-mysql:
    driver: "local"
networks:
  dominion_net:
    ipam:
      driver: default
      config:
        - subnet: "15.16.235.0/24"
        - subnet: "2001:3984:3989::/64"
